version: '3.7'

networks:
  myag:
   name: myag

services:
  websrv1:
    container_name: ws1
    image: nginx:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      #- ./index:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    networks:
      - myag

  websrv2:
    container_name: ws2
    image: nginx:latest
    ports:
      - "8001:80"
    restart: always
    volumes:
      #- ./index:/usr/share/nginx/html
      - ./nginx/default2.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    networks:
     - myag

  phpfpm:
    container_name: phpfpm
    build: .
    volumes:
      - ./php:/var/www/html
    #ports:
    #  - "9000:9000"
    restart: always
    networks:
      - myag



